### ISSUE TITLE
Some issue with SearchActivity

### ISSUE THREAD

**Issue by Aditya664** [Aditya664/Save_The_Life#3]

**Comment by Sagar0-0** [comment]
Modification on the way..

**Comment by Aditya664** [comment]
Fine bro

**Comment by Aditya664** [comment]
Make sure add signed apk file .

**Comment by Sagar0-0** [comment]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/85388413/135831672-6efc6118-1068-4353-a676-d7d53824f98c.PNG">

**Comment by Aditya664** [comment]
Jdk not found

**Comment by Aditya664** [comment]
Change jdk location from project structure

**Comment by Sagar0-0** [comment]
ok now app is working but i am not able to move through branches

**Comment by Sagar0-0** [comment]
Should i add Progress bars in the search and loginactivity??

**Comment by Sagar0-0** [comment]
I clicked on Find donors button too many time, thinking that it is not working but it was actually loading in background so when background task is done it opens soo many search result activities as many times I clicked the button, so it will be much helpful to use progress bar for the responsiveness to be maintained for good ux.

**Comment by Sagar0-0** [comment]
And also app crashes when empty request is made by user so we must add some sanity checks for it.

**Comment by Aditya664** [comment]
> Should i add Progress bars in the search and loginactivity??

Sure

**Comment by Aditya664** [comment]
Make changes whatever you want just make sure app not crash after this

**Comment by Sagar0-0** [comment]
What issue are you facing with SearchActivity?

**Comment by Aditya664** [comment]
Without search its come back to mainactivity

**Comment by Aditya664** [comment]
No any error

**Comment by Sagar0-0** [comment]
I am not facing that... when i click on find donors it do some background work and then intent to Search Result

**Comment by Aditya664** [comment]
Can you send me the apk file please?

**Comment by Sagar0-0** [comment]
Its not possible here..

**Comment by Aditya664** [comment]
LinkedIn

**Comment by Sagar0-0** [comment]
Let me know when it's clear  👍

**Comment by Sagar0-0** [comment]
I think now this issue should be closed 💯
